--- # ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: wagtail-deploy
#   namespace: default
#   labels:
#     name: wagtail-deploy
# spec:
#   type: LoadBalancer
#   ports:
#     - name: http
#       port: 8000
#       targetPort: 8000
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wagtail-deploy
  namespace: default
  labels:
    name: wagtail-app
spec:
  #   type: LoadBalancer
  #   ports:
  #     - name: http
  #       port: 8000
  #       targetPort: 8000

  replicas: 1
  selector:
    matchLabels:
      app: wagtail-app
  template:
    metadata:
      labels:
        app: wagtail-app
    spec:
      imagePullSecrets:
        - name: rbac
      containers:
        - image: azurecr.azurecr.io/wagtail-app:0.0.3.RELEASE
          name: wagtail-ga-container
          resources:
            requests:
              cpu: "200m"
              memory: "32Mi"
          env:
            - name: testEnv
              value: testEnv
          ports:
            - containerPort: 8000
              name: wagtail-app
          imagePullPolicy: Always
      restartPolicy: Always
